[package]
name = "music_tui"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.26.0"
crossterm = "0.27.0"
rodio = "0.17.1"
symphonia = { version = "0.5.3", features = ["all"] }
anyhow = "1.0"
chrono = "0.4"
rand = "0.8"
